#!/usr/bin/env python3
"""List unaddressed コードレビュー / セキュリティレビュー comments on open PRs.

A review comment is unaddressed when it is newer than the PR head commit.
Exit 4 if GitHub cannot be queried (fail closed). Exit 0 otherwise.
"""
from __future__ import annotations

import json
import subprocess
import sys


def gh_json(args: list[str]) -> object:
    try:
        raw = subprocess.check_output(["gh", *args], text=True)
    except subprocess.CalledProcessError as exc:
        print("decision=GH_ERROR")
        print("gh failed:", " ".join(args), file=sys.stderr)
        raise SystemExit(4) from exc
    return json.loads(raw)


def is_review_comment(body: str) -> bool:
    return (
        body.startswith("## コードレビュー結果")
        or body.startswith("## セキュリティレビュー結果")
        or body.startswith("セキュリティレビュー完了")
        or body.startswith("コードレビュー")
        or "_Generated by [Claude Code]" in body
    )


def main() -> int:
    repo = gh_json(["repo", "view", "--json", "nameWithOwner"])
    if not isinstance(repo, dict):
        print("decision=GH_ERROR")
        return 4
    name = repo["nameWithOwner"]
    prs = gh_json(["pr", "list", "--state", "open", "--json", "number,url,headRefOid,title"])
    if not isinstance(prs, list):
        print("decision=GH_ERROR")
        return 4

    unaddressed: list[int] = []
    waiting: list[int] = []
    for pr in prs:
        n = pr["number"]
        comments = gh_json(["api", f"repos/{name}/issues/{n}/comments"])
        commit = gh_json(["api", f"repos/{name}/commits/{pr['headRefOid']}"])
        if not isinstance(comments, list) or not isinstance(commit, dict):
            print("decision=GH_ERROR")
            return 4
        head = commit["commit"]["committer"]["date"]
        reviews = [c for c in comments if is_review_comment(str(c.get("body") or ""))]
        if not reviews:
            print(f"pr #{n} {pr.get('url', '')} no-review-yet")
            waiting.append(n)
            continue
        blocking = []
        for latest in reviews:
            body = str(latest.get("body") or "")
            has_major = "### [Major]" in body
            has_minor = "### [Minor]" in body
            clean = "指摘なし" in body and not has_major and not has_minor
            newer = str(latest.get("created_at") or "") > head
            if newer and (has_major or has_minor) and not clean:
                blocking.append(latest)
        status = "unaddressed" if blocking else "ok"
        newest = max(reviews, key=lambda c: str(c.get("created_at") or ""))
        newest_body = str(newest.get("body") or "")
        print(
            f"pr #{n} {pr.get('url', '')} review={status} "
            f"created={newest.get('created_at')} head={head} "
            f"major={'### [Major]' in newest_body} "
            f"minor={'### [Minor]' in newest_body} "
            f"clean={'指摘なし' in newest_body}"
        )
        if blocking:
            unaddressed.append(n)

    print("unaddressed_prs=" + ",".join(str(x) for x in unaddressed))
    print("waiting_for_review_prs=" + ",".join(str(x) for x in waiting))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
